# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python_service_list.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19python_service_list.proto\"\x12\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\"!\n\rResponseValue\x12\x10\n\x08response\x18\x01 \x01(\t20\n\x06\x45vents\x12&\n\x0bListOneItem\x12\x05.Item\x1a\x0e.ResponseValue\"\x00\x42-Z+/python_service/genpb/python_service_deleteb\x06proto3')



_ITEM = DESCRIPTOR.message_types_by_name['Item']
_RESPONSEVALUE = DESCRIPTOR.message_types_by_name['ResponseValue']
Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
  'DESCRIPTOR' : _ITEM,
  '__module__' : 'python_service_list_pb2'
  # @@protoc_insertion_point(class_scope:Item)
  })
_sym_db.RegisterMessage(Item)

ResponseValue = _reflection.GeneratedProtocolMessageType('ResponseValue', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEVALUE,
  '__module__' : 'python_service_list_pb2'
  # @@protoc_insertion_point(class_scope:ResponseValue)
  })
_sym_db.RegisterMessage(ResponseValue)

_EVENTS = DESCRIPTOR.services_by_name['Events']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z+/python_service/genpb/python_service_delete'
  _ITEM._serialized_start=29
  _ITEM._serialized_end=47
  _RESPONSEVALUE._serialized_start=49
  _RESPONSEVALUE._serialized_end=82
  _EVENTS._serialized_start=84
  _EVENTS._serialized_end=132
# @@protoc_insertion_point(module_scope)
